import "@maxsparrow/sigma/src/renderers/sigma.renderers.webgl.js"
import "@maxsparrow/sigma/src/renderers/sigma.renderers.def.js"
import "@maxsparrow/sigma/src/renderers/webgl/sigma.webgl.nodes.def.js"
import "@maxsparrow/sigma/src/renderers/webgl/sigma.webgl.nodes.fast.js"
import "@maxsparrow/sigma/src/renderers/webgl/sigma.webgl.edges.def.js"
import "@maxsparrow/sigma/src/renderers/webgl/sigma.webgl.edges.fast.js"
import "@maxsparrow/sigma/src/renderers/webgl/sigma.webgl.edges.arrow.js"
